### ISSUE TITLE
Fehlermeldung "Invalid format string" 

### ISSUE THREAD

**Issue by cma5** [ID-Start-Winter22/chat-team-11#35]
```shell
C:\Users\Markus\Documents\Studium\HM\chat-team-11\rasa\actions\actions.py:35: DeprecationWarning: invalid escape sequence \s
  regex_result = re.findall("((ECE|ICE|EC|IC|RE|THA|RJ|FLX|HBX|WB|D|EN|NJ|DN|IRE|MEX|RE|FEX|RB|S)(\s|)(\d{1,5}))", latest_message)
2022-12-08 10:18:46 INFO     rasa_sdk.executor  - Registered function for 'action_print_train_id'.
2022-12-08 10:18:46 INFO     rasa_sdk.executor  - Registered function for 'action_store_train_data'.
2022-12-08 10:18:46 INFO     rasa_sdk.executor  - Registered function for 'action_train_data_change'.
2022-12-08 10:18:46 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
2022-12-08 10:19:53 ERROR    rasa_sdk.endpoint  - Exception occurred during execution of request <Request: POST /webhook>
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "C:\Users\Markus\miniconda3\envs\rasaenv\lib\site-packages\rasa_sdk\endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "C:\Users\Markus\miniconda3\envs\rasaenv\lib\site-packages\rasa_sdk\executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "C:\Users\Markus\Documents\Studium\HM\chat-team-11\rasa\actions\actions.py", line 53, in run
    f" **Abfahrtszeit:** {prettify_time(train_data['departure']['scheduledTime'])}\n" \
  File "C:\Users\Markus\Documents\Studium\HM\chat-team-11\rasa\actions\api_functions.py", line 58, in prettify_time
    time_day_and_time = time.strftime("heute (%d.%m.%Y) um %-H:%M Uhr")
ValueError: Invalid format string
```

**Comment by theopfr** [comment]
Kannst du steps zum reproducen hinzufügen? Was hast du gemacht, um den Fehler zu triggern @cma5

**Comment by theopfr** [comment]
Issues in der Wiki: https://github.com/ID-Start-Winter22/chat-team-11/wiki/%F0%9F%8F%83%E2%80%8D%E2%99%82%EF%B8%8F-Ideation-und-Sprint-1#-issues
